config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    gitlab.com/louise.cordrie/DT-LAVA-WF:
      branch: main
      repo: https://gitlab.com/louise.cordrie/DT-LAVA-WF
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      gitlab.com/louise.cordrie/DT-LAVA-WF git:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-apricot-ant.sh
        container: qc.acc_seedy-xanthic-newfoundland
  QC.Doc:
    repos:
      gitlab.com/louise.cordrie/DT-LAVA-WF find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.lumpy-wisteria-ibis.sh
        container: qc.doc_zippy-wisteria-maltese
      gitlab.com/louise.cordrie/DT-LAVA-WF git:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-pear-octopus.sh
        container: qc.doc_silly-carmine-squirrel
      gitlab.com/louise.cordrie/DT-LAVA-WF markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-viridian-liger.sh
        container: qc.doc_jumpy-maroon-scorpion
  QC.Lic:
    repos:
      gitlab.com/louise.cordrie/DT-LAVA-WF licensee:
        commands:
        - /usr/bin/env sh .sqa/script.bluesy-ecru-deer.sh
        container: qc.lic_sloppy-charcoal-peccary
  QC.Sec:
    repos:
      gitlab.com/louise.cordrie/DT-LAVA-WF bandit:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-cinnabar-hare.sh
        container: qc.sec_gimpy-periwinkle-setter
  QC.Sty:
    repos:
      gitlab.com/louise.cordrie/DT-LAVA-WF flake8:
        commands:
        - /usr/bin/env sh .sqa/script.sleepy-asparagus-hound.sh
        container: qc.sty_grumpy-tangerine-sparrow
      gitlab.com/louise.cordrie/DT-LAVA-WF jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.frumpy-scarlet-mist.sh
        container: qc.sty_lousy-fuchsia-dachsbracke
      gitlab.com/louise.cordrie/DT-LAVA-WF oclint:
        commands:
        - /usr/bin/env sh .sqa/script.lousy-beige-salamander.sh
        container: qc.sty_queasy-flax-rat
  QC.Uni:
    repos:
      gitlab.com/louise.cordrie/DT-LAVA-WF pytest:
        commands:
        - /usr/bin/env sh .sqa/script.beady-zucchini-goat.sh
        container: qc.uni_hasty-crimson-mau
  QC.Ver:
    repos:
      gitlab.com/louise.cordrie/DT-LAVA-WF get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-blue-newfoundland.sh
        container: qc.ver_pokey-periwinkle-mammoth
timeout: 5400
