config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    gitlab.com/louise.cordrie/DT-LAVA-WF:
      branch: main
      repo: https://gitlab.com/louise.cordrie/DT-LAVA-WF
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      gitlab.com/louise.cordrie/DT-LAVA-WF git:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-blue-kangaroo.sh
        container: qc.acc_clammy-khaki-lemming
  QC.Doc:
    repos:
      gitlab.com/louise.cordrie/DT-LAVA-WF find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-smalt-bear.sh
        container: qc.doc_frumpy-jade-bullfrog
      gitlab.com/louise.cordrie/DT-LAVA-WF git:
        commands:
        - /usr/bin/env sh .sqa/script.frumpy-champagne-pinscher.sh
        container: qc.doc_muzzy-black-woodpecker
      gitlab.com/louise.cordrie/DT-LAVA-WF markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.pasty-purple-jellyfish.sh
        container: qc.doc_crabby-vermilion-labradoodle
  QC.Lic:
    repos:
      gitlab.com/louise.cordrie/DT-LAVA-WF licensee:
        commands:
        - /usr/bin/env sh .sqa/script.whiny-periwinkle-otter.sh
        container: qc.lic_muggy-salmon-dolphin
  QC.Sec:
    repos:
      gitlab.com/louise.cordrie/DT-LAVA-WF bandit:
        commands:
        - /usr/bin/env sh .sqa/script.flaky-cream-donkey.sh
        container: qc.sec_stealthy-magenta-llama
  QC.Sty:
    repos:
      gitlab.com/louise.cordrie/DT-LAVA-WF flake8:
        commands:
        - /usr/bin/env sh .sqa/script.greasy-grey-bloodhound.sh
        container: qc.sty_trippy-red-sponge
      gitlab.com/louise.cordrie/DT-LAVA-WF jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-fuchsia-quetzal.sh
        container: qc.sty_tasty-coral-husky
      gitlab.com/louise.cordrie/DT-LAVA-WF oclint:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-puce-shark.sh
        container: qc.sty_sickly-ruby-baboon
  QC.Uni:
    repos:
      gitlab.com/louise.cordrie/DT-LAVA-WF pytest:
        commands:
        - /usr/bin/env sh .sqa/script.trippy-aqua-earwig.sh
        container: qc.uni_homey-cerulean-burmese
  QC.Ver:
    repos:
      gitlab.com/louise.cordrie/DT-LAVA-WF get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.shabby-brown-beetle.sh
        container: qc.ver_baggy-wheat-albatross
timeout: 5400
