config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    gitlab.com/louise.cordrie/DT-LAVA-WF:
      branch: ST530101
      repo: https://gitlab.com/louise.cordrie/DT-LAVA-WF/
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      gitlab.com/louise.cordrie/DT-LAVA-WF git:
        commands:
        - /usr/bin/env sh .sqa/script.wimpy-white-wolf.sh
        container: qc.acc_cranky-green-axolotl
  QC.Doc:
    repos:
      gitlab.com/louise.cordrie/DT-LAVA-WF find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-periwinkle-scorpion.sh
        container: qc.doc_sleepy-plum-bombay
      gitlab.com/louise.cordrie/DT-LAVA-WF git:
        commands:
        - /usr/bin/env sh .sqa/script.hazy-orange-ibis.sh
        container: qc.doc_cozy-champagne-cichlid
  QC.Lic:
    repos:
      gitlab.com/louise.cordrie/DT-LAVA-WF licensee:
        commands:
        - /usr/bin/env sh .sqa/script.jumpy-green-flounder.sh
        container: qc.lic_sloppy-lilac-olm
  QC.Sec:
    repos:
      gitlab.com/louise.cordrie/DT-LAVA-WF bandit:
        commands:
        - /usr/bin/env sh .sqa/script.gimpy-goldenrod-maltese.sh
        container: qc.sec_pasty-cream-devil
  QC.Sty:
    repos:
      gitlab.com/louise.cordrie/DT-LAVA-WF flake8:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-tan-kingfisher.sh
        container: qc.sty_homely-goldenrod-saola
  QC.Uni:
    repos:
      gitlab.com/louise.cordrie/DT-LAVA-WF pytest:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-sepia-uakari.sh
        container: qc.uni_squeaky-green-bear
  QC.Ver:
    repos:
      gitlab.com/louise.cordrie/DT-LAVA-WF get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.stealthy-chartreuse-gorilla.sh
        container: qc.ver_muzzy-aquamarine-beetle
timeout: 5400
