config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    gitlab.com/louise.cordrie/DT-LAVA-WF:
      branch: main
      repo: https://gitlab.com/louise.cordrie/DT-LAVA-WF/
      subfolder: WF5301/ST530101
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      gitlab.com/louise.cordrie/DT-LAVA-WF git:
        commands:
        - /usr/bin/env sh .sqa/script.queasy-green-hyrax.sh
        container: qc.acc_flabby-myrtle-cuscus
  QC.Doc:
    repos:
      gitlab.com/louise.cordrie/DT-LAVA-WF find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.sleazy-brown-guppy.sh
        container: qc.doc_snazzy-emerald-kingfisher
      gitlab.com/louise.cordrie/DT-LAVA-WF git:
        commands:
        - /usr/bin/env sh .sqa/script.lumpy-amethyst-panda.sh
        container: qc.doc_sickly-periwinkle-whale
      gitlab.com/louise.cordrie/DT-LAVA-WF markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.woolly-smalt-snail.sh
        container: qc.doc_snoopy-yellow-moose
  QC.Lic:
    repos:
      gitlab.com/louise.cordrie/DT-LAVA-WF licensee:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-flax-mule.sh
        container: qc.lic_snappy-brown-armadillo
  QC.Sec:
    repos:
      gitlab.com/louise.cordrie/DT-LAVA-WF bandit:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-scarlet-fousek.sh
        container: qc.sec_gimpy-grey-booby
  QC.Sty:
    repos:
      gitlab.com/louise.cordrie/DT-LAVA-WF flake8:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-lemon-macaque.sh
        container: qc.sty_gimpy-peach-husky
      gitlab.com/louise.cordrie/DT-LAVA-WF jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-bronze-affenpinscher.sh
        container: qc.sty_hazy-cinnabar-bandicoot
      gitlab.com/louise.cordrie/DT-LAVA-WF oclint:
        commands:
        - /usr/bin/env sh .sqa/script.stealthy-crimson-barnacle.sh
        container: qc.sty_wimpy-plum-tarantula
  QC.Uni:
    repos:
      gitlab.com/louise.cordrie/DT-LAVA-WF pytest:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-violet-moth.sh
        container: qc.uni_stinky-cinnabar-otter
  QC.Ver:
    repos:
      gitlab.com/louise.cordrie/DT-LAVA-WF get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-periwinkle-ibis.sh
        container: qc.ver_crappy-burgundy-uguisu
timeout: 5400
