config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    gitlab.com/louise.cordrie/DT-LAVA-WF:
      branch: main
      repo: https://gitlab.com/louise.cordrie/DT-LAVA-WF
      subfolder: DTC53/WF5301/ST530101/src
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      gitlab.com/louise.cordrie/DT-LAVA-WF git:
        commands:
        - /usr/bin/env sh .sqa/script.sickly-myrtle-flamingo.sh
        container: qc.acc_queasy-ochre-donkey
  QC.Doc:
    repos:
      gitlab.com/louise.cordrie/DT-LAVA-WF find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.gamy-purple-gorilla.sh
        container: qc.doc_seedy-cornflower-dunker
      gitlab.com/louise.cordrie/DT-LAVA-WF git:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-xanthic-cheetah.sh
        container: qc.doc_gimpy-platinum-baboon
      gitlab.com/louise.cordrie/DT-LAVA-WF markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.wimpy-yellow-axolotl.sh
        container: qc.doc_blurry-copper-mouse
  QC.Lic:
    repos:
      gitlab.com/louise.cordrie/DT-LAVA-WF licensee:
        commands:
        - /usr/bin/env sh .sqa/script.bluesy-scarlet-liger.sh
        container: qc.lic_clammy-grey-barb
  QC.Sec:
    repos:
      gitlab.com/louise.cordrie/DT-LAVA-WF bandit:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-mauve-tetra.sh
        container: qc.sec_pasty-mustard-quoll
  QC.Sty:
    repos:
      gitlab.com/louise.cordrie/DT-LAVA-WF flake8:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-silver-toad.sh
        container: qc.sty_boozy-sangria-cattle
      gitlab.com/louise.cordrie/DT-LAVA-WF jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-burgundy-tang.sh
        container: qc.sty_wheezy-magnolia-burmese
      gitlab.com/louise.cordrie/DT-LAVA-WF oclint:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-dandelion-bongo.sh
        container: qc.sty_woolly-myrtle-hummingbird
  QC.Uni:
    repos:
      gitlab.com/louise.cordrie/DT-LAVA-WF commands:
        commands:
        - /usr/bin/env sh .sqa/script.pokey-maroon-hornet.sh
        container: qc.uni_seedy-peach-chicken
  QC.Ver:
    repos:
      gitlab.com/louise.cordrie/DT-LAVA-WF get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.beady-cornflower-toucan.sh
        container: qc.ver_tacky-smalt-crocodile
timeout: 5400
